name: Check downstream compiles

on:
  push:
    branches:
      - zkvm
  pull_request:
    branches:
      - zkvm

jobs:
  check-downstream-compiles:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: sphinx
            path: ""
          - repo: zk-light-clients
            path: aptos
          - repo: zk-light-clients
            path: ethereum
    steps:
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/ci-workflows
          path: ci-workflows
      - uses: ./ci-workflows/.github/actions/ci-env
      - uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/sphinx
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
        with:
          repository: argumentcomputer/${{ matrix.repo }}
          path: ${{ github.workspace }}/${{ matrix.repo }}
          token: ${{ secrets.REPO_TOKEN }}
      - uses: ./ci-workflows/.github/actions/check-downstream-compiles
        with:
          upstream-path: "bls12_381"
          downstream-path: "${{ matrix.repo }}/${{ matrix.path }}"
